name: Covid Collection

on:
  schedule:
  # At minute 5 past every 4th hour on every day-of-week from Monday through Friday.
    - cron: "5 */4 * * 1-5"

  workflow_dispatch:
jobs:
  build:
    name: Build on Mac OS
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      - run: yarn install
      - run: yarn compile
      - uses: nanasess/setup-chromedriver@v1
        #with:
        # Optional: do not specify to match Chrome's version
        # chromedriver-version: '88.0.4324.96'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - run: yarn getCovid
      - run: ls -lha

      - id: set_var
        run: |
          content=`cat ./covid.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=covidStats::$content"
        # env:
        #   COVID_STATS: testing
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          # text: ${{fromJson(steps.set_var.outputs.covidStats)}}
          text: This is pacelholder text
          details: Test Succeeded!
          description: Some Info.
          webhookUrl: ${{ secrets.DISCORD_UPDATE_WEBHOOK }}
