name: Covid Collection

on:
  push:
    branches:
      - dev
  # schedule:
  # run At minute 5 past every 4th hour on every day-of-week from Monday through Friday.
  #  - cron: "5 */3 * * 1-5"
  

  workflow_dispatch:
jobs:
  build:
    name: Build on Mac OS
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      - run: yarn install
      - run: yarn compile
      - uses: nanasess/setup-chromedriver@v1
        #with:
        # Optional: do not specify to match Chrome's version
        # chromedriver-version: '88.0.4324.96'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - run: yarn getCovid
      # - run: ls -lha
      
      - uses: EndBug/add-and-commit@v8 # You can change this to use a specific version.
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: 'covid.json'

          # The local path to the directory where your repository is located. You should use actions/checkout first to set it up.
          # Default: '.'

          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default: github_actor
          default_author: github_actor

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          # message: 'Your commit message'

          # If this input is set, the action will push the commit to a new branch with this name.
          # Default: ''
          # new_branch: custom-new-branch

          # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
          # - ignore -> errors will be logged but the step won't fail
          # - exitImmediately -> the action will stop right away, and the step will fail
          # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
          # Default: ignore
          pathspec_error_handling: ignore

          # Arguments for the git pull command. By default, the action does not pull.
          # Default: ''
          # pull: '--rebase --autostash ...'

          # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
          # Default: true
          # push: false

          # The arguments for the `git rm` command (see the paragraph below for more info)
          # Default: ''
          # remove: './dir/old_file.js'

          # Arguments for the git tag command (the tag name always needs to be the first word not preceded by an hyphen)
          # Default: ''
          # tag: 'v1.0.0 --force'
            

      
      - id: set_var
        run: |
          content=`cat ./covid.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=covidStats::$content"
        # env:
        #   COVID_STATS: testing
      - name: Notify Via Discord
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          # text: ${{fromJson(outputs.covidStats.data)}}
          text: ${{steps.set_var.outputs.covidStats}} # This actually works.
          # text: ${{fromJson(steps.set_var.outputs.covidStats)}}
          # text: This is pacelholder text
          details: Automated Collection & Reporting Succeeded!
          description: SpyD's Covid Stats Bot.
          webhookUrl: ${{ secrets.DISCORD_UPDATE_WEBHOOK }}
